image: {}
  #repository: data61/
  #tag: latest
  #pullPolicy: Always#
autoscaler:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
resources:
  requests:
    cpu: 10m
    memory: 30Mi
  limits:
    cpu: 100m
service:
  type: NodePort

helmet:
  frameguard: false
  
csp:
  browserSniff: false
  directives:
    scriptSrc:
    - "''self''"
    - "''unsafe-inline''"
    - browser-update.org
    - "blob:"
    objectSrc:
    - "''none''"
    workerSrc:
    - "''self''"
    - "blob:"

cors: 
  exposedHeaders:
  - "Content-Range"
  - "X-Content-Range"