apiVersion: v1
kind: ConfigMap
metadata:
  name: "web-app-config"
data:
  # When the config map is mounted as a volume, these will be created as files.
  web.json: '{
    {{- if .Values.fallbackUrl -}} "fallbackUrl": {{ .Values.fallbackUrl | quote }}, {{- end -}}
    "baseUrl": {{ .Values.baseUrl | default "/" | quote }}
  }'
  helmet.json: '{{ toJson .Values.helmet | indent 2 }}'
  cors.json: '{{ toJson .Values.cors | indent 2 }}'
  csp.json: '{{ toJson .Values.csp | indent 2 }}'
